#!/usr/bin/env python3

YMLS = [
    "week1.yml",
    "week2.yml",
    "week3.yml",
    "week4.yml",
    "week5.yml",
    "week6.yml",
    "week7.yml",
    "week8.yml",
    "week9.yml",
    "week10.yml",
    "week11.yml",
    "week12.yml",
    "week13.yml",
    "week14.yml",
    "week15.yml",
    "rrr.yml",
    "finals.yml",
]
OUT = "schedule.yml"

print("Updating %s." % OUT)
final = ""
for yml in YMLS:
    with open(yml, "r") as f:
        final += f.read()
        if not final[-1] == "\n":
            final += "\n"

with open(OUT, "w") as f:
    f.write(
        "# THIS FILE WAS AUTOGENERATED! Update the respective week*.yml files and run `./gen_yaml.py`\n"
    )
    f.write(final)

print("Done.")
